version: "3.1"
 
services:
 
  beopen-dashboard:
    image: idraopendata/idra-portal:v1.1.0
    restart: always
    ports:
      - '127.0.0.1:4200:80'
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf